[package]
name = "astro_compute_swisseph"
version = "0.1.0"
authors = ["Stéphane Bressani <s.bressani@bluewin.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
