[package]
name = "astro"
version = "0.1.0"
authors = ["Stéphane Bressani <s.bressani@bluewin.ch>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["lib", "staticlib"]

[[bin]]
name = "yew"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
libswe-sys = { path = "lib/libswe-sys" }
yew = "0.10.0"

[build-dependencies]
cbindgen = "0.12"
